In [90]:

# calling required libraries

import numpy as np
import time
import warnings
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.utils import shuffle
from sklearn.preprocessing import normalize
from sklearn.metrics import confusion_matrix, precision_recall_fscore_support
from keras.utils import to_categorical
from keras import models, layers
from keras.utils import to_categorical
from keras.models import Sequential
model = Sequential()

In [97]:
data = 'https://archive.ics.uci.edu/ml/machine-learning-databases/heart-disease/processed.cleveland.data'
df = pd.read_csv(data, sep=',' , header = None)
df.columns = ["age", "sex", "cp", "treshbps", "chol", "fbs", "restecg", "thalach",
              "exang", "oldpeak", "slope", "ca", "thal", "num"]

#df.rename_axis('.').rename_axis("ID", axis="columns")

df.index.name = 'id'

# Fill missing data with columnwise median values
df = df.fillna(df.median())

# Randomize rows
df = shuffle(df)
df.tail()

# Scale the data
#df_min = df.min()
#df_max = df.max()
#df_norm = (df - df_min)/(df_max - df_min)
#DOESENT WORK!

#df_min = df.min()
#df_max = df.max()
#df_norm = (df - df_min)/(df_max - df_min)
df.head()

ValueError: operands could not be broadcast together with shapes (606,) (2,) 

In [8]:
df.index

RangeIndex(start=0, stop=303, step=1, name='id')

In [87]:
df.to_csv('Case1.2_wille.csv')

#If you look at the CSV there, you should see it has the headers. 
#df.to_csv('Case1.2_wille.csv', header=False)

# Or you whatn to save file as HTML
#df.to_html('Case1.2_wille.html')

In [93]:
x = df.iloc[:, 4].values
y = df.iloc[:, 0].values
num = df.iloc[:, 13].values

In [81]:
x

array([233., 286., 229., 250., 204., 236., 268., 354., 254., 203., 192.,
       294., 256., 263., 199., 168., 229., 239., 275., 266., 211., 283.,
       284., 224., 206., 219., 340., 226., 247., 167., 239., 230., 335.,
       234., 233., 226., 177., 276., 353., 243., 225., 199., 302., 212.,
       330., 230., 175., 243., 417., 197., 198., 177., 290., 219., 253.,
       266., 233., 172., 273., 213., 305., 177., 216., 304., 188., 282.,
       185., 232., 326., 231., 269., 254., 267., 248., 197., 360., 258.,
       308., 245., 270., 208., 264., 321., 274., 325., 235., 257., 216.,
       234., 256., 302., 164., 231., 141., 252., 255., 239., 258., 201.,
       222., 260., 182., 303., 265., 188., 309., 177., 229., 260., 219.,
       307., 249., 186., 341., 263., 203., 211., 183., 330., 254., 256.,
       407., 222., 217., 282., 234., 288., 239., 220., 209., 258., 227.,
       204., 261., 213., 250., 174., 281., 198., 245., 221., 288., 205.,
       309., 240., 243., 289., 250., 308., 318., 29

In [82]:
y

array([63., 67., 67., 37., 41., 56., 62., 57., 63., 53., 57., 56., 56.,
       44., 52., 57., 48., 54., 48., 49., 64., 58., 58., 58., 60., 50.,
       58., 66., 43., 40., 69., 60., 64., 59., 44., 42., 43., 57., 55.,
       61., 65., 40., 71., 59., 61., 58., 51., 50., 65., 53., 41., 65.,
       44., 44., 60., 54., 50., 41., 54., 51., 51., 46., 58., 54., 54.,
       60., 60., 54., 59., 46., 65., 67., 62., 65., 44., 65., 60., 51.,
       48., 58., 45., 53., 39., 68., 52., 44., 47., 53., 53., 51., 66.,
       62., 62., 44., 63., 52., 59., 60., 52., 48., 45., 34., 57., 71.,
       49., 54., 59., 57., 61., 39., 61., 56., 52., 43., 62., 41., 58.,
       35., 63., 65., 48., 63., 51., 55., 65., 45., 56., 54., 44., 62.,
       54., 51., 29., 51., 43., 55., 70., 62., 35., 51., 59., 59., 52.,
       64., 58., 47., 57., 41., 45., 60., 52., 42., 67., 55., 64., 70.,
       51., 58., 60., 68., 46., 77., 54., 58., 48., 57., 52., 54., 35.,
       45., 70., 53., 59., 62., 64., 57., 52., 56., 43., 53., 48

In [94]:
num

array([1, 0, 1, 4, 1, 0, 4, 0, 2, 0, 2, 0, 0, 0, 0, 0, 1, 0, 2, 1, 2, 0,
       2, 2, 0, 1, 0, 0, 0, 0, 1, 0, 2, 2, 1, 0, 2, 0, 0, 3, 1, 0, 0, 1,
       0, 0, 0, 3, 0, 0, 0, 0, 1, 1, 3, 1, 1, 3, 2, 1, 1, 0, 0, 0, 3, 3,
       2, 0, 0, 0, 3, 1, 0, 0, 1, 2, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 3,
       0, 0, 0, 0, 0, 2, 0, 0, 3, 0, 1, 0, 0, 0, 2, 2, 1, 1, 0, 1, 3, 0,
       0, 0, 0, 4, 1, 0, 0, 3, 0, 0, 1, 0, 2, 0, 4, 0, 0, 2, 2, 0, 4, 3,
       0, 1, 3, 0, 3, 2, 3, 2, 3, 0, 0, 3, 1, 0, 3, 0, 1, 1, 0, 0, 0, 3,
       3, 0, 1, 0, 2, 3, 2, 0, 3, 0, 1, 0, 0, 1, 0, 0, 0, 0, 2, 0, 0, 0,
       2, 0, 1, 1, 4, 4, 4, 4, 0, 3, 0, 0, 1, 0, 1, 0, 1, 0, 0, 2, 2, 2,
       3, 3, 0, 2, 0, 0, 0, 2, 0, 0, 3, 0, 2, 0, 0, 4, 0, 1, 1, 1, 0, 0,
       1, 0, 1, 2, 0, 0, 1, 1, 3, 0, 0, 0, 4, 3, 0, 0, 0, 3, 0, 0, 0, 0,
       2, 2, 1, 3, 0, 0, 0, 1, 0, 0, 1, 0, 3, 0, 0, 0, 0, 0, 0, 2, 0, 0,
       0, 3, 0, 2, 1, 0, 1, 0, 1, 0, 0, 0, 3, 0, 0, 0, 0, 4, 0, 1, 0, 0,
       1, 0, 0, 3, 1, 0, 0, 3, 4, 0, 1, 0, 0, 0, 2,