In [10]:
import numpy as np
import pandas as pd

import os
print(os.listdir("A:/Downloads/retinopathy-dataset-master"))

['newTrainLabels.csv', 'nosymptoms', 'README.md', 'retinopathy_solution.csv', 'symptoms']


In [11]:
df = pd.read_csv("A:/Downloads/retinopathy-dataset-master/retinopathy_solution.csv")
df.head()

image  level    Usage
0   1_left      0  Private
1  1_right      0  Private
2   2_left      0   Public
3  2_right      0   Public
4   3_left      2  Private

In [12]:
from sklearn.metrics import cohen_kappa_score, confusion_matrix, classification_report
from numpy.random import randint, randn

In [13]:
# Read the true labels
y_true = df['level'].values

# Generate randomness
y_random = np.round(y_true + randn(len(y_true)))
# Limit the random label values between 0 and 4
y_random = np.maximum(y_random, 0)
y_random = np.minimum(y_random, 4)

# Calculate and print confusion matrix
cm = confusion_matrix(y_true, y_random)
print('Confusion matrix:')
print(cm)
print('')

# Calculate and print Cohen's kappa score
k = cohen_kappa_score(y_true, y_random, weights = 'quadratic')
print("Quadratic weighted Cohen's kappa score = {:.4f}".format(k))
print('')

# Calculate and print classification report
cp = classification_report(y_true, y_random)
print('Classification report:')
print(cp)

Confusion matrix:
[[27366  9532  2390   228    17]
 [ 1165  1430   927   222    18]
 [  552  1845  2984  1934   546]
 [    6    68   289   451   400]
 [    0     8    74   321   803]]

Quadratic weighted Cohen's kappa score = 0.7063

Classification report:
              precision    recall  f1-score   support

           0       0.94      0.69      0.80     39533
           1       0.11      0.38      0.17      3762
           2       0.45      0.38      0.41      7861
           3       0.14      0.37      0.21      1214
           4       0.45      0.67      0.54      1206

   micro avg       0.62      0.62      0.62     53576
   macro avg       0.42      0.50      0.42     53576
weighted avg       0.78      0.62      0.68     53576



# Conclusion

We were able to read the labels from csv-file, calculate the confusion matrix, Cohen's kappa, and classification report against slightly random labels.