In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory

import os
print(os.listdir("../../retinopathy-dataset-master"))

# Any results you write to the current directory are saved as output.

['nosymptoms', 'README.md', 'symptoms']


In [2]:
# Import opencv and matplot libraries
import cv2
import matplotlib.pyplot as plt

In [3]:
# Read the solution list
df = pd.read_csv('../../retinopathy-dataset-master/retinopathy_solution.csv')
df.head()

image  level    Usage
0   1_left      0  Private
1  1_right      0  Private
2   2_left      0   Public
3  2_right      0   Public
4   3_left      2  Private

In [4]:
# Import the metrics and random integer generator
from sklearn.metrics import cohen_kappa_score, confusion_matrix, classification_report
from numpy.random import randint, randn

In [6]:
# Read the true labels
y_true = df['level'].values

# Generate randomness
y_random = np.round(y_true + randn(len(y_true)))
# Limit the random label values between 0 and 4
y_random = np.maximum(y_random, 0)
y_random = np.minimum(y_random, 4)

# Calculate and print confusion matrix
cm = confusion_matrix(y_true, y_random)
print('Confusion matrix:')
print(cm)
print('')

# Calculate and print Cohen's kappa score
k = cohen_kappa_score(y_true, y_random, weights = 'quadratic')
print('')

# Calculate and print classification report
cp = classification_report(y_true, y_random)
print('Classification report:')
print(cp)

Confusion matrix:
[[27297  9566  2435   224    11]
 [ 1137  1466   899   241    19]
 [  546  1874  3021  1879   541]
 [    6    77   306   478   347]
 [    0     7    69   287   843]]


Classification report:
              precision    recall  f1-score   support

           0       0.94      0.69      0.80     39533
           1       0.11      0.39      0.18      3762
           2       0.45      0.38      0.41      7861
           3       0.15      0.39      0.22      1214
           4       0.48      0.70      0.57      1206

   micro avg       0.62      0.62      0.62     53576
   macro avg       0.43      0.51      0.44     53576
weighted avg       0.78      0.62      0.68     53576

